@startuml
'https://plantuml.com/class-diagram

class Cliente{
    int id
    String nome
    String telefone
    String email
}
class Agendamento{
    int id
    DateTime horario
    Carro carro
    Servico servico
}
class Carro{
int id
Cliente proprietario
String modelo
String cor
String placa

}
abstract class Servico

Cliente <- Carro
Agendamento <- Servico
Carro <- Agendamento

@enduml